# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
codecov: true
coveralls: true
os:
  - linux
  - osx
  # - windows
julia:
  - 0.6
  - 1.0
  - 1.3
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly

# uncomment the following lines to override the default test script
script:
  - export JL_PKG=StringLiterals
  - julia --color=yes --inline=no -e "if VERSION < v\"0.7.0-DEV.5183\"; Pkg.clone(pwd()); Pkg.build(\"${JL_PKG}\");
    else using Pkg; if VERSION >= v\"1.1.0-rc1\"; Pkg.build(verbose=true); else Pkg.build(); end; end"
  - julia --check-bounds=yes --color=yes --inline=no -e "if VERSION < v\"0.7.0-DEV.5183\"; Pkg.test(\"${JL_PKG}\", coverage=true);
    else using Pkg; Pkg.test(coverage=true); end"
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'p="https://github.com/JuliaString"; s=".jl.git"; l="_Entities"; Pkg.clone("$p/StrTables$s"); t=("LaTeX","Emoji","HTML","Unicode"); for n in t; Pkg.clone("$p/$n$l$s"); end;  Pkg.clone("$p/Format$s"); Pkg.clone(pwd()); Pkg.add("LightXML"); Pkg.add("JSON"); for n in t; Pkg.build("$n$l"); end; Pkg.test("StringLiterals"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e "VERSION >= v\"0.7.0-DEV.5183\" && using Pkg; cd(Pkg.dir(\"${JL_PKG}\")); Pkg.add(\"Coverage\"); using Coverage; Coveralls.submit(Coveralls.process_folder())"
  # push coverage results to Codecov
  - julia -e "VERSION >= v\"0.7.0-DEV.5183\" && using Pkg; cd(Pkg.dir(\"${JL_PKG}\")); Pkg.add(\"Coverage\"); using Coverage; Codecov.submit(Codecov.process_folder())"
